AGRFrontend/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Web.Configuration;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

using VGRental.Model;
using System.Threading.Tasks;

namespace AGRFrontend.Controllers
{
    [Authorize]
    public class SubscriptionController : Controller
    {
        //
        // GET: /Subscription/
        public ActionResult Index()
        {
            string connection_string
                = WebConfigurationManager.ConnectionStrings["EC2Connection"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connection_string))
            {
                using (SqlCommand command = new SqlCommand("Command String", connection))
                {
                    command.CommandText = "SELECT customerID, SubscriptionID, Price, "
                    + "ExpirationDate, Description FROM Subscriptions";
                    try
                    {
                        connection.Open();
                        List<Subscription> subscriptions = new List<Subscription>();
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                string username = "";

                                using (SqlConnection customer_connection = new SqlConnection(connection_string))
                                {
                                    SqlCommand customer_command = new SqlCommand("Command String",
                                        customer_connection);
                                    customer_command.CommandText = "SELECT UserName FROM Customers where "
                                    + "customerID = @customerID";
                                    customer_command.Parameters.AddWithValue("@customerID", reader["customerID"]);

                                    customer_connection.Open();
                                    using (SqlDataReader customer_reader
                                        = customer_command.ExecuteReader())
                                    {
                                        customer_reader.Read();
                                        username = customer_reader["UserName"].ToString();
                                    }
                                    customer_connection.Close();
                                }
                                subscriptions.Add(new Subscription
                                {
                                    customerID = Convert.ToInt32(reader["customerID"]),
                                    SubscriptionID = Convert.ToInt32(reader["SubscriptionID"]),
                                    Price = Convert.ToSingle(reader["Price"]),
                                    ExpirationDate = Convert.ToDateTime(reader["ExpirationDate"]),
                                    Description = reader["Description"].ToString(),
                                    Customer = new Customer
                                    {
                                        UserName = username,
                                    },
                                });
                            }
                        }

                        connection.Close();
                        return View(subscriptions);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e.ToString());
                        return View(new List<Subscription>());
                    }
                }
            }
        }

        //
        // GET: /Subscription/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Subscription/Create
        public ActionResult Create()
        {
            string connection_string
                = WebConfigurationManager.ConnectionStrings["EC2Connection"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connection_string))
            {
                SqlCommand command = new SqlCommand("Command String", connection);
                command.CommandText = "SELECT customerID, UserName FROM Customers "
                    + "where UserName = @UserName";
                SqlParameter UserName = new SqlParameter("@UserName", User.Identity.GetUserName());
                command.Parameters.Add(UserName);
                try
                {
                    connection.Open();
                    Subscription subscription = new Subscription();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        reader.Read();
                        subscription.customerID = Convert.ToInt32(reader["customerID"]);
                        subscription.ExpirationDate = DateTime.UtcNow.AddMonths(1);
                        subscription.Price = 7F;
                        subscription.Description
                            = string.Format("Unlimited rentals for ${0}/month",
                            subscription.Price);
                        subscription.Customer = new Customer
                        {
                            UserName = reader["UserName"].ToString(),
                        };
                    }

                    connection.Close();
                    return View(subscription);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                    return View();
                }
            }
        }

        //
        // POST: /Subscription/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Subscription new_subscription)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string connection_string
                        = WebConfigurationManager.ConnectionStrings["EC2Connection"].ConnectionString;

                    using (SqlConnection connection = new SqlConnection(connection_string))
                    {
                        using (SqlCommand command
                            = new SqlCommand("INSERT INTO Subscriptions (customerID, "
                            + "SubscriptionID, Price, ExpirationDate, Description) "
                            + "Values (@customerID, @SubscriptionID, @Price, "
                            + "@ExpirationDate, @Description)", connection))
                        {
                            command.Parameters.AddWithValue("@customerID",
                                new_subscription.customerID);
                            command.Parameters.AddWithValue("@SubscriptionID",
                                new_subscription.SubscriptionID);
                            command.Parameters.AddWithValue("@Price",
                                new_subscription.Price);
                            command.Parameters.AddWithValue("@ExpirationDate",
                                new_subscription.ExpirationDate);
                            command.Parameters.AddWithValue("@Description",
                                new_subscription.Description);

                            try
                            {
                                connection.Open();
                                if (command.ExecuteNonQuery() != 1)
                                    throw new Exception("The number of new users created isn't equal to 1");

                                connection.Close();
                            }
                            catch (Exception e)
                            {
                                Console.WriteLine(e.ToString());
                            }
                        }
                    }

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            // If we got this far, something failed, redisplay form
            return View(new_subscription);
        }

        //
        // GET: /Subscription/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Subscription/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Subscription/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Subscription/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AGRFrontend/Views/Subscription/Create.cshtml
@model VGRental.Model.Subscription
@{
    ViewBag.Title = "Subscribe";
}

<h2>@ViewBag.Title.</h2>
@using Microsoft.AspNet.Identity
@using System.Globalization
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Create", "Subscription", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>Subscribe to AGR.</h4>
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.Label("Your ID", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.customerID,
                new { @class = "col-md-2 control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Customer.UserName,
            new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Customer.UserName,
                new { @class = "col-md-2 control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Price,
                new { @class = "col-md-2 control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ExpirationDate,
            new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.ExpirationDate,
                new { @class = "col-md-2 control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description,
            new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Description,
                new { @readonly="readonly", @class = "col-md-2 control-label" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Subscribe" />
            </div>
        </div>
    }
}
else
{
    <h2>Sign in to subscribe to AGR.</h2>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AGRFrontend/Views/Subscription/Index.cshtml
@model IEnumerable<VGRental.Model.Subscription>

@{
    ViewBag.Title = "Subscriptions";
}

<h2>@ViewBag.Title.</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.customerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.customerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.customerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.customerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.customerID })
            </td>
        </tr>
    }
</table>